//buildscript {
//    repositories {
//        maven {
//            url = uri("https://plugins.gradle.org/m2/")
//        }
//    }
//    dependencies {
//        classpath("org.barfuin.gradle.taskinfo:gradle-taskinfo:2.1.0")
//    }
//}
//plugins {
//    id("org.barfuin.gradle.taskinfo") version "2.1.0"
//}

//本地的插件依赖和仓库, 只能将仓库和依赖地址写入到buildscript中, 否则会报错
buildscript {
    repositories {
        maven { url "$rootDir/lib/release" }
    }
    dependencies {
        classpath "com.self:library:1.1"
    }
}


// -*- coding: utf-8 -*-

plugins {
    id 'java'
    id 'application'
    id 'java-library'
    id 'groovy'
    id 'maven-publish'
}
//本地插件依赖, 只能以apply plugin的方式引入, 否则会报错
apply plugin: 'com.self.custom-plugin-d'
apply plugin: 'com.self.custom-plugin-e'

'com.self'
version '1.0-SNAPSHOT'

repositories {
    //导入依赖时, 会先从本地gradle缓存中查找, 如果没有再从配置的仓库中依次向下查找
    mavenCentral()
}
println 'reportDir is ' + reportsDir//或者也可以写成: println "reportDir is ${reportsDir}"
//reportDir是在java插件中定义的, 用于存放测试报告

//apply plugin:   'com.self.custom-plugin-e'

//'com.self'
//version '1.0-SNAPSHOT'


//mainClassName = 'com.self.MultipleMain'

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'

    //1.依赖当前项目下的某个模块[子工程]
    implementation project(":gradle03-subproject01")
    //2.直接依赖本地的某个jar文件, 文件集合的形式
    implementation files('libs/foo.jar', 'libs/bar.jar')
    //2.配置某文件夹作为依赖项, 文件树的形式
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    //3.直接依赖,简写
    implementation 'org.apache.logging.log4j:log4j:2.22.0'
    //3.直接依赖,完整写法
    //implementation group: 'org.apache.logging.log4j', name: 'log4j', version: '2.22.0'
    implementation 'org.projectlombok:lombok:1.18.30'
//    implementation('org.hibernate:hibernate-core:3.6.3.Final') {
//        //排除某一个库(slf4j)依赖:如下三种写法都行
//        exclude group: 'org.slf4j'
//        exclude module: 'slf4j-api'
//        exclude group: 'org.slf4j', module: 'slf4j-api'
//    }
//    implementation('org.hibernate:hibernate-core:3.6.3.Final') {
//        //不使用传递性依赖, 只引入当前依赖, 不引入当前依赖的依赖, 不推荐使用
//        transitive = false
//    }
    implementation('org.slf4j:slf4j-api:+')
    //使用最新版本的依赖, 或者写成: implementation('org.slf4j:slf4j-api:latest.release')//或者是latest.integration
    implementation('org.hibernate:hibernate-core:3.6.3.Final')

    // Log4j2 API and Core
//    implementation 'org.apache.logging.log4j:log4j-api:2.17.1'
//    implementation 'org.apache.logging.log4j:log4j-core:2.17.1'

    // Bridge SLF4J API calls to Log4j2
//    implementation 'org.apache.logging.log4j:log4j-slf4j-impl:2.17.1'
}

test {
    useJUnitPlatform()
}

//configurations.all() {
//    Configuration configuration ->
//        //当遇到版本冲突时直接构建失败
//        configuration.resolutionStrategy.failOnVersionConflict()
//}
apply from: 'utils.gradle'
apply from: 'tasks.gradle'
apply from: 'vision.gradle'

class GreetingPlugin implements Plugin<Project> {
    void apply(Project project) {
        project.task('plugin1') {
            doLast {
                println 'Hello from the GreetingPlugin'
            }
        }
    }
}


// 通过gradle plugin1执行
apply plugin: GreetingPlugin


interface GreetingPluginExtension {
    Property<String> getMessage()

    Property<String> getGreeter()
}

class GreetingPlugin1 implements Plugin<Project> {
    void apply(Project project) {
        // 添加新的扩展到扩展容器中, 名称为plugin2container, 类型为GreetingPluginExtension
        // 还有一个可变参数constructionArguments: 用于构造扩展实例的参数。这是一个可变参数列表，允许在创建扩展实例时传入构造函数所需的参数。
        def extension = project.extensions.create('plugin2container', GreetingPluginExtension)
        project.task('plugin2') {
            doLast {
                // 通过扩展容器获取扩展实例
                println "${extension.message.get()} from ${extension.greeter.get()}"
            }
        }
    }
}

apply plugin: GreetingPlugin1

// 配置扩展的值
plugin2container {
    message = 'Hi'
    greeter = 'Gradle'
}

//会在所有项目中创建task37
allprojects {
    tasks.register('task37') {
        println "task37 from the ${project.name} allproject"
    }
}

//只会在子项目中创建task38
subprojects {
    tasks.register('task38') {
        println "task38 from the ${project.name} subproject"
    }
}

//只会在gradle03-subproject01子项目中创建task39, 项目名称必须再settings.gradle中定义
project(':gradle03-subproject01') {
    //需要先使用apply plugin的方式引入插件, 否则会报错, 不支持plugins{}的方式
    apply plugin: 'java'
    //可以在指定的子项目中引入插件
    dependencies {
        implementation 'org.projectlombok:lombok:1.18.30'
    }
    //也可以指定一些其他的配置
    tasks.register('task39') {
        println "task39 from the ${project.name} subproject"
    }
}


//带源码和javadoc的发布:需要'java-library'插件支持:它是java的升级版，java插件的功能java-library都有
javadoc.options.encoding = "UTF-8"
java {
    //发布jar包时, 会自动发布javadoc
    withJavadocJar()
    //发布jar包时, 会自动发布源码
    withSourcesJar()
}
publishing {
    publications {
        myLibrary(MavenPublication) {
            groupId = 'com.self.sample' //指定GAV坐标信息
            artifactId = 'library'
            version = '1.1'
            from components.java//发布jar包
//            from components.web///引入war插件，发布war包
        }
    }
    repositories {
        //本地仓库位于USER_HOME/.m2/repository mavenLocal()
        // 发布项目到私服中
        maven {
            name = 'myRepo' //name属性可选,表示仓库名称，url必填
            // 发布地址:可以是本地仓库或者maven私服
            // url = layout.buildDirectory.dir("repo")
            // change URLs to point to your repos, e.g. http://my.org/repo
            def releasesRepoUrl = layout.buildDirectory.dir('repos/releases')
            def snapshotsRepoUrl = layout.buildDirectory.dir('repos/snapshots')
            url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
            //认证信息:用户名和密码
            //credentials {
            //    username = 'joe'
            //    password = 'secret'
            //}
        }
    }
}

