// -*- coding: utf-8 -*-
plugins {
    id 'java'
    id 'application'
    id 'java-library'
}

'com.self'
version '1.0-SNAPSHOT'


repositories {
    mavenCentral()
}

mainClassName = 'com.self.MultipleMain'

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'

    //1.依赖当前项目下的某个模块[子工程]
    implementation project(":gradle03-subproject01")
    //2.直接依赖本地的某个jar文件, 文件集合的形式
    implementation files('libs/foo.jar', 'libs/bar.jar')
    //2.配置某文件夹作为依赖项, 文件树的形式
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    //3.直接依赖,简写
//    implementation 'org.apache.logging.log4j:log4j:2.22.0'
    //3.直接依赖,完整写法
    //implementation group: 'org.apache.logging.log4j', name: 'log4j', version: '2.22.0'
    implementation 'org.projectlombok:lombok:1.18.30'
    implementation 'org.apache.logging.log4j:log4j-core:2.22.0'
}

test {
    useJUnitPlatform()
}

apply from: 'utils.gradle'
apply from: 'tasks.gradle'

