// -*- coding: utf-8 -*-
plugins {
    id 'java'
    id 'application'
}

'com.self'
version '1.0-SNAPSHOT'


repositories {
    mavenCentral()
}

mainClassName = 'com.self.MultipleMain'

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
}

test {
    useJUnitPlatform()
}

apply from: 'utils.gradle'
apply from: 'tasks.gradle'

