task "taks1" {
    //任务的配置:配置阶段执行
    println "config task1"
    //任务的执行:在执行阶段执行先执行doFirst,后执行doLast
    doFirst {
        println "do first"
    }
    doLast {
        println "do last"
    }
}
task "task1_1" {
    //任务的依赖:在执行task1_1之前先执行task1
    group = "group"
    dependsOn tasks."taks1"
    //任务的配置:配置阶段执行,
    println("config task1_1")
    doFirst {
        println "do first task1_1"
    }
    doLast {
        println "do last task1_1"
    }
}
//在task外部定义doFirst、doLast行为
taks1.doFirst {
    println it.description
}
task1_1.doLast {
    println "group " + it.group
}


def map = new HashMap<>();
//action属性可以设置为闭包，设置task自身的行为,key只能是action
map.put("action", { println "task2.." })
//map.put("action2",{println "task2.."})
task(map, "task2") {
    description 'task2 description	'
    group "custom group"
    //在task内部定义doFirst、doLast行为
    doFirst {
        def name = 'doFirst task2'
        println name
    }
    doLast {
        def name = 'doLast task2'
        println name
    }
}
//在task外部定义doFirst、doLast行为
task2.doFirst {
    println it.description
}
task2.doLast {
    println it.group
}
//task2的执行结果是
//task2 description
//doFirst task2
//task2..
//doLast task2
//com.self

//idea中有些task没有绿色箭头, 可以使用./gradlew -i task名 来执行-i可打印详细的信息
tasks.register("task3") {
    println "task3"
    doFirst {
        println "do first task3"
    }
    doLast {
        println "do last task3"
    }
    println("config task3")
}

//任务的依赖
//1.参数依赖
task task4 {
    doLast {
        println "Task4.."
    }
}
task 'task5' {
    doLast {
        println "Task5.."
    }
}
//参数方式依赖: dependsOn后面用冒号
task task6(dependsOn: [task4, task5]) {
    doLast {
        println "Task6.."
    }
}
//会先执行task4,task5,再执行task6

//2.内部依赖
task task7 {
    doLast {
        println "Task7.."
    }
}
task task8 {
    doLast {
        println "Task8.."
    }
}
//内部依赖: dependsOn后面()内传参, 用空格或者等号都可以, dependsOn只是依赖, 如果有重复的, 那么只会执行一次
task task9 {
    dependsOn(task7, task8)
    dependsOn task7, task8
    dependsOn = [task7, task8]
    doLast {
        println "Task9.."
    }
}

//3.外部依赖
task task10 {
    doLast {
        println "Task10.."
    }
}
task task11 {
    doLast {
        println "Task11.."
    }
}
task task12 {
    doLast {
        println "Task12.."
    }
}
//同样的, 外部依赖也可以用空格也可以用等号, 依赖的任务也只会执行一次
task12.dependsOn task10, task11
task12.dependsOn(task10, task11)
task12.dependsOn = [task10, task11]

//通过task的create方法创建任务
//gradle  任务名是缩写:  任务名支持驼峰式命名风格的任务名缩写，如：taskTask13  简写为：tT或者tT13, 执行任务 gradle tT, gradle tT13
tasks.create("taskTask13") {
    doLast {
        println "Task13.."
    }
}

//通过tasks的register方法创建任务,这种方式创建的任务是延迟创建的,只有在被调用时才会执行, 其他的方式创建的任务是在build的时候就会执行
tasks.register("task14") {
    doLast {
        println "Task14.."
    }
}

//在定义任务时也可以给任务分配属性：定义任务的时候可以直接指定任务属性，也可以给已有的任务动态分配属性：
task(group: "custom group", description: "task15 description", "task15") {
    doLast {
        println "Task15.."
    }
}
//给已有的任务在内部分配属性
task("task16") {
    group = "custom group"
    description = "task16 description"
    doLast {
        println "Task16.."
    }
}

//在已有的任务外部分配属性
task task17 {
    doLast {
        println "Task17.."
    }
}
task17.group = "custom group"

//下面这行代码会使clean任务的group属性变为custom group
//clean.group("custom group")

tasks.register("task18", Delete) {
    //先创建一个文件
    doFirst {
        file("task18.txt").createNewFile()
    }
    Thread.sleep(5000)
    //删除文件
    delete file("task18.txt")
    //删除build目录,只会删除当前项目的build目录
    buildDir.deleteDir()
//    delete(buildDir)
//    delete(rootProject.buildDir)
    //删除所有项目的build目录, 8.5 版本gralde的 buildDir是getLayout().getBuildDirectory()
    delete(rootProject.allprojects.buildDir)
}

//自定义的task
class CustomTask extends DefaultTask {
//@TaskAction表示Task本身要执行的方法
    @TaskAction
    def doSelf() {
        println "CustomTask 自身 在执行的in doSelf"
    }
}

//自定义的task启动名称是myDefinitionTask而不是task19 , task19只是一个实例, MyDefinitionTask并没有被显式的定义
def task19 = task MyDefinitionTask(type: CustomTask)
task19.doFirst() {
    println "MyDefinitionTask 执行之前 执行的 doFirst方法"
}
task19.doLast() {
    println "MyDefinitionTask 执行之后 执行的 doLast方法"
}

//调用自定义的CustomTask
task(task20, type: CustomTask) {
    doFirst {
        println "doFirst Task20.."
    }
    doLast {
        println "doLast Task20.."
    }
}
//动态分配任务
4.times { counter ->
    // 0, 1, 2, 3, for循环, counter是循环的变量
    tasks.register("taskDynamic$counter") {
        //动态创建任务
        doLast {
            println "I'm taskDynamic number $counter"
        }
    }
}
//可以使用它在运行时动态地向任务添加依赖项
tasks.named('taskDynamic0') { dependsOn('taskDynamic2', 'taskDynamic3') }

//任务的启用和禁用
task task21 {
    doLast {
        println 'This task is Executing...'
    }
    //默认情况下，任务是启用的，可以通过enabled属性或者方法来禁用任务,false时任务会被跳过执行显示SKIPPED
    enabled(false)//直接设置任务开启，默认值为true
}
//task21.enabled = false //设置关闭任务

//任务的超时
task task22() {
    doLast {
        Thread.sleep(1000)
        println "当前任务" + it.name + "执行了"
    }
    timeout = Duration.ofMillis(500)
}
task task23() {
    doLast {
        println "当前任务" + it.name + "执行了"
    }
}
//在控制台执行gradle task22 task23, 会发现task22会报错, 超时了, 所以没有继续执行task23
//但是在控制台输入gradle task22 task23 --continue, 会发现task22超时了, 但是task23还是会执行

//任务的查找
//1.通过名称查找
task task24 {
    doLast {
        println "Task24.."
    }
}
//通过名称查找
def task25 = tasks.getByName("task24")
task25.doLast {
    println "Task24 getByName.." + it.name //it.name是task24
}
//2.通过路径查找
tasks.findByPath("task24").doLast {
    println "Task24 findByPath.."
}
//通过名称查找,如果找不到会报错


//任务的规则
task task26 {
    doLast {
        println "task26 Hello, World!"
    }
}

//规则是为了简化构建脚本的编写，它可以根据一定的规则自动创建任务，而不需要我们手动创建
//如果执行noExistTask任务,会报错,但是如果使用规则,就不会报错,会执行规则中的内容
//下面的全局规则要小心使用, 因为会创建隐藏任务, 属性似乎也会被创建
//tasks.addRule("noneTask") { String taskName ->
//    task(taskName) {
//        doLast {
//            println "该${taskName}任务不存在，请查证后再执行"
//        }
//    }
//}

//如果代码中没有pingAnyServer相关的方法, 在控制台执行./gradlew pingAnyServer, 会发现打印了Pinging: AnyServer
tasks.addRule("Pattern: ping<ID>") { String taskName ->
    if (taskName.startsWith("ping") && !project.tasks.findByName(taskName)) {
        task(taskName) {
            doLast {
                println "Pinging: " + (taskName - 'ping')
            }
        }
    }
}

//如果执行./gradlew groupPing, 就算代码中没有pingServer1和pingServer2相关的方法, 也不会报错, 基于规则的任务上创建 dependentOn 关系
tasks.register('groupPing') {
    dependsOn 'pingServer1', 'pingServer2'
}

//在执行./gradlew task27 -Pattr时不会执行task27(-P{attr}是传参)
//注意一些创建隐藏任务的方法, 比如上面的 tasks.addRule("noneTask"), 会创建隐藏任务,也包括attr属性
// 在执行!project.hasProperty("attr"), 会创建一个任务, 这个时候打印properties, 会发现有一个attr属性
task task27 {
    doLast {
        println "Task27.."
    }
}

task27.onlyIf {
    //只有当返回true时才会执行task27
    !project.hasProperty("attr")
}

//当你运行 gradle 命令而没有指定特定的任务时，Gradle 将会执行在 defaultTasks 属性中指定的任务。
//在大多数项目中，存在一组核心的构建任务，这些任务通常被认为是项目的主要构建任务。这可能包括编译代码、运行测试、生成文档等。
// 通过使用 defaultTasks 属性,你可以定义在运行 gradle 命令时默认执行的任务集合，这些任务通常是项目的主要构建任务。
//比如下面两个任务, 在执行./gradlew时, 且没有指定任务名, 会执行task28和task29
defaultTasks 'task28', 'task29'
tasks.register('task28') {
    doLast {
        println "Task28.."
    }
}
tasks.register('task29') {
    doLast {
        println "Task29.."
    }
}

//文件操作
task task30 {
    //使用 Project.file(java.lang.Object)方法，通过指定文件的相对路径或绝对路径来对文件的操作,其中相对路径为相对当前project[根project 或者子project]的目录
    //相对路径, 创建文件
    File configFile = file("src/main/resources/file-operate/conf-realtive.xml")
    configFile.createNewFile()
    //绝对路径, 创建文件
    File configFile2 = file("D:\\JAVA\\javaProject\\Groovy\\gradle03-multiple\\src\\main\\resources\\file-operate\\conf-absolute.xml")
    configFile2.createNewFile()
    //使用java的File类创建文件
    File configFile3 = new File("src/main/resources/file-operate/conf-java.xml")
    configFile3.createNewFile()
}

//文件集合
task task31 {
    doLast {
        //文件集合就是一组文件的列表,在Gradle中,文件集合用FileCollection接口表示。我们可以使用 Project.files(java.lang.Object...)方法，
        ConfigurableFileCollection fileCollection = files("src/main/resources/file-operate/conf-collection1.xml", "src/main/resources/file-operate/conf-collection2.xml", "src/main/resources/file-operate/conf-collection3.xml")
        fileCollection.forEach {
            it.createNewFile()
            println it.name
        }

        Set fileSet1 = fileCollection.files
        //as关键字可以将一个对象转换为另一个对象,这里将FileCollection转换为Set
        Set fileSet2 = fileCollection as Set
        println("检查文件是否存在")
        for (final def item in fileSet2) {
            String exist = item.exists() ? "存在" : "不存在"
            println item.name + "文件:" + exist
        }

        println("文件集合的操作")
        def unionFileCollection = fileCollection + files("src/main/resources/file-operate/conf-collection4.xml")
        println("unionFileCollection:" + unionFileCollection.files.forEach { println it.name })
        def minusFileCollection = fileCollection - files("src/main/resources/file-operate/conf-collection3.xml")
        println("minusFileCollection:" + minusFileCollection.files.forEach { println it.name })
    }
}

//文件树的操作
task 'task32' {
    doLast {
        println("文件树的操作")
        //使用 Project.fileTree(java.lang.Object)方法，通过指定文件的相对路径或绝对路径来对文件的操作,其中相对路径为相对当前project[根project 或者子project]的目录
        println("通过路径获取文件树")
        def fileTreeRootPath = "src/main/resources/file-tree-operate"
        fileTree(fileTreeRootPath).forEach {
            println it.name
        }
        //使用路径创建文件树对象，同时指定包含的文件
        println("通过路径创建文件树对象，同时指定包含的文件")
        fileTree(fileTreeRootPath).include("**/*.java").forEach {
            println it.name
        }

        //通过闭包创建文件树
        println("通过闭包创建文件树")
        fileTree(fileTreeRootPath) {
            include '**/*.java'
            exclude('**/a-1.java')
        }.forEach {
            println it.name
        }

        //通过路径和闭包创建文件树：具名参数给map传值
        println("通过路径和闭包创建文件树")
        fileTree(dir: fileTreeRootPath, includes: ['**/*.java']).forEach {
            println it.name
        }
    }
}

//文件拷贝, 如果不写在配置阶段, 会无法执行, 提示: > Task :[任务名] NO-SOURCE
//不知道为什么, 这个任务只有在执行./gradlew task33时才会执行, 在配置阶段不会执行
task task33(type: Copy) {
    //可以是文件,也可以是文件夹,如果是文件夹,只会拷贝文件夹下的文件,不会拷贝这个文件夹
    from 'src/main/resources/file-tree-operate/a-java'
    from('src/main/resources/file-tree-operate/a-txt') {
        exclude '**/a-1.txt'
    }
    //重命名文件, 将指定文件重命名为指定的文件名, fileName是一个String
    rename { String fileName ->
        fileName.replace('a-2', 'a-2-rename')
    }
    from zipTree('src/main/resources/file-tree-operate/a-zip/a-zip.zip')//解压zip文件到into目录
    into 'src/main/resources/file-generate' //必须是文件夹
}

//这样写copy任务的话, 类似build, clean这些java插件自带的任务, 会和自带的任务一起执行, 比如clean会执行这个copy任务
//source_set_tasks说明: https://docs.gradle.org/current/userguide/java_plugin.html#java_source_set_tasks
task task34 {
    copy {
        //可以是文件,也可以是文件夹,如果是文件夹,只会拷贝文件夹下的文件,不会拷贝这个文件夹
        from 'src/main/resources/file-tree-operate/a-java'
        from('src/main/resources/file-tree-operate/a-txt') {
            exclude '**/a-1.txt'
        }
        //重命名文件, 将指定文件重命名为指定的文件名, fileName是一个String
        rename { String fileName ->
            fileName.replace('a-2', 'a-2-rename')
        }
        from zipTree('src/main/resources/file-tree-operate/a-zip/a-zip.zip')//解压zip文件到into目录
        into 'src/main/resources/file-generate' //必须是文件夹
        println('task34执行完成')
    }
}

//copy {
//    //可以是文件,也可以是文件夹,如果是文件夹,只会拷贝文件夹下的文件,不会拷贝这个文件夹
//    from 'src/main/resources/file-tree-operate/a-java'
//    from('src/main/resources/file-tree-operate/a-txt') {
//        exclude '**/a-1.txt'
//    }
//    //重命名文件, 将指定文件重命名为指定的文件名, fileName是一个String
//    rename { String fileName ->
//        fileName.replace('a-2', 'a-2-rename')
//    }
//    from zipTree('src/main/resources/file-tree-operate/a-zip/a-zip.zip')//解压zip文件到into目录
//    into 'src/main/resources/file-generate' //必须是文件夹
//}

//归档文件
//ZIP: https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Zip.html#org.gradle.api.tasks.bundling.Zip
//Zip，Tar，Jar，War 和Ear 的生成都是通过 ArchiveTask 类来实现的，这些任务都继承自 Copy 类，因此，它们都具有 Copy 类的所有功能。
task task35(type: Zip) {
    doLast {
        from('src/main/resources/file-tree-operate')
        //into方法没有作用, 最终生成的zip文件会在build/distributions目录下
        //into('src/main/resources/file-generated')
        //指定文件夹
        destinationDirectory = file('src/main/resources/file-archive')
        //指定文件名称, 默认名称为[archiveBaseName]-[archiveAppendix]-[archiveVersion]-[archiveClassifier].[archiveExtension]
        archiveFileName = 'myZip.zip'
    }
}

task task36 {
    doLast {
        //通过Project.zipTree(java.lang.Object)方法，将一个zip文件转换为一个文件树
        //.visit方法遍历文件树,可以获取文件夹的名称,文件的名称, 直接forEach只能获取文件的名称
        zipTree('src/main/resources/file-archive/myZip.zip').visit {
            println it.name
        }
        //如果压缩包myZip.zip是在项目的build/distributions目录下, 可以直接使用zipTree('myZip.zip')来获取文件树
    }
}