plugins {
    id 'java'
}

group 'com.self'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
}

test {
    useJUnitPlatform()
}
//不同的子项目可以有相同的任务名,在执行时会执行所有相同任务名的任务
task("task3"){
    dependsOn(":gradle03-subproject01:task3")
    println "task subproject02"
}