server:
  profiles:
    active: dev
  port: 7778

spring:
  application:
    name: service-order
  datasource:
    username: postgres
    password: zQy2iQp5
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gradle-microservice-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
