plugins {
    //插件添加了对 Groovy 语言的支持，允许你用 Groovy 编写项目的构建逻辑，包括自定义的任务、插件等。
    id 'groovy'
    //插件提供了一系列用于开发 Gradle 插件的便利功能，包括自动应用 java 插件、设置插件的元数据、以及简化插件的打包和发布过程。
    //如果你正在开发一个 Gradle 插件，这个插件会帮助你正确地设置项目结构和生成所需的插件描述文件(META-INF/gradle-plugins/*.properties)。它确保插件按照 Gradle 的要求被打包和识别。
    id 'java-gradle-plugin'
}

dependencies {
    //这个依赖项提供了 Gradle API 的访问，允许你在插件或构建脚本中使用 Gradle 自身的类和方法。
    implementation gradleApi() //必须
    //这个依赖项提供了对本地 Groovy 环境的支持，它包含了运行 Groovy 代码所需的库。
    implementation localGroovy() //必须
}

repositories {
    google()
    mavenCentral() //必须
}

//把项目入口设置为src/main/groovy(可以不写)
//https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSet.html
//sourceSets {
//    main {
//        groovy {
//            srcDir 'src/main/groovy'
//        }
//    }
//}


gradlePlugin {
    plugins {
        pluginA {
            //插件的 ID，用于在项目中应用插件
            id = 'com.self.custom-plugin-a'
            //插件的实现类，用于在项目中应用插件
            implementationClass = 'com.self.CustomPluginA'
        }
        pluginB {
            id = 'com.self.custom-plugin-b'
            implementationClass = 'com.self.CustomPluginB'
        }
    }
}