plugins {
    id 'java'
}

group 'com.self'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    //
//    implementation('org.slf4j:slf4j-api:1.4.1!! ')
}
test {
    useJUnitPlatform()
}

task("task3"){
    println "task subproject01"
}

task "task4" {
    //尝试读取父工程的ext中定义的扩展属性company
    println "access parent project ext.company: " + project.parent.ext.company
}
